config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/profile', to: 'users#profile'
  post '/trips/create', to: 'trips#create'
  resources :trips
  root to: 'trips#index'

  namespace :api do
    post '/search', to: 'trips#search'
    post '/requests/approve', to: 'requests#approve'
    post '/requests/create', to: 'requests#create'
  end

end

app/views/layouts/_footer.html.erb
<div class="row navbar-footer" style="margin:0px;">
  <div class="navbar-footer">
      <p class="navbar-text" style="padding-left:20px;">© 2016 - Site Built By @ajoered - <a href="https://ajoered.com">www.ajoered.com</a>
      </p>
      <a href="https://github.com/alvarojoered" class="navbar-btn btn-default btn pull-right">Github</a>
  </div>
</div>

app/views/layouts/_footer_fixed.html.erb
<div class="row navbar-footer-fixed" style="margin:0px;">
  <div class="navbar-footer-fixed">
      <p class="navbar-text" style="padding-left:20px;">© 2016 - Site Built By @ajoered - <a href="https://ajoered.com">www.ajoered.com</a>
      </p>
      <a href="https://github.com/alvarojoered" class="navbar-btn btn-default btn pull-right">Github</a>
  </div>
</div>

app/views/layouts/_footer_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-90346448-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <% if user_signed_in? %>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-left navbar-image"><img src="https://res.cloudinary.com/drzsplf7y/image/upload/v1481712896/final_logo_white_hf14ex.png" class="navbar-image"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/">Home</a>
        </li>
        <li>
          <a data-scroll href="#search-button" class="find-trip">Find Trips</a>
        </li>
        <li>
          <a href="/trips/new">Create Trips</a>
        </li>
        <li>
          <%= link_to current_user.name, profile_path %>
        </li>
        <li>
          <%= link_to 'Sign out', destroy_user_session_path, method: 'DELETE' %>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
    <% else %>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-left navbar-image"><img src="https://res.cloudinary.com/drzsplf7y/image/upload/v1481712896/final_logo_white_hf14ex.png" class="navbar-image"></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/">Home</a>
        </li>
        <li>
          <a data-scroll href="#search-button" class="find-trip">Find Trips</a>
        </li>
        <li>
          <a href="/trips/new">Create Trips</a>
        </li>
        <li>
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
        <li>
          <%= link_to 'Sign in', new_user_session_path %>
        </li>
      </ul>
    </div>
    <% end %>
  </div>
  <!-- /.container -->
</nav>

<script>
   $(function() {
      $('.nav li a').click(function() {
         $('.nav li').removeClass();
         $($(this).attr('href')).addClass('active');
      });
   });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GOSURF</title>
  <%= csrf_meta_tags %>
  <script src="https://cdn.jsdelivr.net/sweetalert2/6.2.1/sweetalert2.min.js">
  </script>
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCwMfMENTf8PU8inF6lG48nSv3spe0g5-M&libraries=places">
  </script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.2.1/sweetalert2.min.css">
<link href="https://fonts.googleapis.com/css?family=Dekko" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Architects+Daughter" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">


  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

</head>

<body>
<%= render "layouts/navbar" %>

    <%= yield %>

</body>
</html>